from .base import BaseSolver
from .structural import StructuralSolver
from .thermal import ThermalSolver
from .convection import ConvectionSolver
from .vibration import VibrationSolver
from .gravity import GravitySolver
from .stress import StressConstrainedSolver
from .maxlength import MaxLengthSolver
from .multi import MultiPhysicsSolver